### PR TITLE
Fix permission not showing up on iOS15

### PR DESCRIPTION
**Pull request by steve-rock**

### CODE REVIEW

**Comment by mrousavy** [comment]
Code looks good, can you confirm that this works on both iOS 15+ and iOS 14 and below?

**Review by BDDev — APPROVED** [review]
LGTM!

**Comment by steve-rock** [comment]
> Code looks good, can you confirm that this works on both iOS 15+ and iOS 14 and below?

Yes, it works well on both iOS15+ and iOS14 and below.

**Comment by zbarbuto** [comment]
@mrousavy would it be possible to get this published as a new npm version please?

**Pull request merged**
